<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.Reporting" Version="2.1.0" />
		<PackageReference Include="ClosedXML" Version="0.95.4" />
		<PackageReference Include="Mapster" Version="7.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="6.0.0" />
		<PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="6.0.0" />
		<PackageReference Include="Microsoft.ReportingServices.ReportViewerControl.WebForms" Version="150.1484.0" />
		<PackageReference Include="NodaTime" Version="3.0.9" />
		<PackageReference Include="QRCoder" Version="1.4.1" />
		<PackageReference Include="RabbitMQ.Client" Version="6.3.0" />
		<PackageReference Include="System.Data.OleDb" Version="6.0.0" />
		<PackageReference Include="System.Drawing.Common" Version="6.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.14.1" />
		<PackageReference Include="System.ServiceModel.Duplex" Version="4.9.0" />
		<PackageReference Include="System.ServiceModel.Http" Version="4.9.0" />
		<PackageReference Include="System.ServiceModel.NetTcp" Version="4.9.0" />
		<PackageReference Include="System.ServiceModel.Security" Version="4.9.0" />
		<PackageReference Include="Xabe.FFmpeg" Version="5.0.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Core\Core.csproj" />
	  <ProjectReference Include="..\DB\DB.csproj" />
	  <ProjectReference Include="..\DTO\DTO.csproj" />
	  <ProjectReference Include="..\Helpers\Helpers.csproj" />
	  <ProjectReference Include="..\IServiceContractor\IServiceContractor.csproj" />
	  <ProjectReference Include="..\Localization\Localization.csproj" />
		</ItemGroup>
	
</Project>
